title:            Deepali Jain
tagline:          Attempting to figuring out the universe.
description:      AI Resident, Google AI, New York
# Comment out url when working locally to resolve base urls correctly
# url: jaindeepali.github.io

# Owner/author information
owner:
  name:           Deepali Jain
  avatar:         avatar.png
  bio:            "Developer"
  email:          jaindeepali811@gmail.com
  twitter:        Deepali01140419        
  github:         jaindeepali       
  disqus:         jaindeepali-blog
  facebook:       deepalijain8
  google-plus:    +DeepaliJain811
  location:       "New York, USA"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /publications
    external: true
  - title: Publications
    url: /publications
  - title: Github
    url: https://github.com/jaindeepali
    external: true
  - title: CV
    url: /assets/resume/Deepali_Jain_CV.pdf
    external: true
  - title: Mail
    url: mailto:jaindeepali811@gmail.com
    external: true
  # - title: Google Scholar
  #   url: https://scholar.google.co.in/citations?user=ZHj4_X4AAAAJ&hl=en&oi=ao
  #   external: true
  # - title: RSS
  #   url: /feed.xml

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   enable_coderay: false

#   coderay:
#     coderay_line_numbers: 
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: class

plugins:
  - jekyll-feed
  - jekyll-gist

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
